# Training configuration for pong
# Core training parameters
total_timesteps: 5000000
learning_rate: 0.00025
buffer_size: 500000
learning_starts: 5000
batch_size: 512
exploration_fraction: 0.2
target_update_interval: 1000
frame_stack: 4

# Network architecture
policy: "CnnPolicy"
features_extractor: "NatureCNN"
features_dim: 256

# Preprocessing
normalize_images: true
grayscale: true
resize_shape: [84, 84]

# Environment settings
frame_skip: 4
noop_max: 30

# Evaluation settings
eval_episodes: 100
eval_deterministic: true
render_eval: false

# Logging
tensorboard_log: true
save_freq: 50000
log_interval: 100
